variable "location" {}
variable "resource_group_name" {}
variable "aks_name" {}
variable "subnet_aks" {}
variable "node_count" {}
variable "vm_size" {}
variable "max_pods" {}
variable "appgw_name" {}
variable "subnet_appgw" {}
variable "kubernetes_version" {}
variable "vnet_id" {}
